setting:
  name: "test_ncd_128"
  output_root: "./experiments"
  pc_path: "./data/ncd_128/cloister/ply"
  pose_path: "./data/ncd_128/cloister/poses.txt" 
  deskew: True
process:
  min_range_m: 1.5
  max_range_m: 60.0
  min_z_m: -10.0
  vox_down_m: 0.08
  adaptive_range_on: True
sampler:
  surface_sample_range_m: 0.35
  surface_sample_n: 3
  free_sample_begin_ratio: 0.3
  free_sample_end_dist_m: 1.2
  free_front_sample_n: 2 
neuralpoints:
  voxel_size_m: 0.3
  search_alpha: 0.5
  weighted_first: False
loss:
  sigma_sigmoid_m: 0.1
  loss_weight_on: True
  dist_weight_scale: 0.8
  ekional_loss_on: True
  weight_e: 0.5
continual:
  batch_size_new_sample: 3000
  pool_capacity: 1e7
tracker:
  source_vox_down_m: 0.6
  iter_n: 100
  valid_nn_k: 5
pgo:
  map_context: True
  context_cosdist: 0.3
  pgo_freq_frame: 30
  min_loop_travel_ratio: 3.0
optimizer: # mapper
  iters: 15
  batch_size: 16384
eval:
  wandb_vis_on: False # log to wandb or not
  o3d_vis_on: True # visualize the mapping or not
  silence_log: True
  mesh_freq_frame: 50 # reconstruct the mesh every x frames
  mesh_min_nn: 15
  save_map: True