setting:
  name: "sanity_test"
  output_root: "./experiments"
  pc_path: "./data/kitti_example/sequences/00/velodyne"
process:
  max_range_m: 60.0
tracker:
  iter_n: 20
eval:
  o3d_vis_on: False # visualize the mapping or not
  silence_log: True # output the logs or not
  save_map: True
