setting:
  name: "sanity_test"
  output_root: "./experiments"
  pc_path: "./data/kitti_example/sequences/00/velodyne"
process:
  max_range_m: 60.0
tracker:
  track_on: True
  iter_n: 20
eval:
  o3d_vis_on: True # visualize the mapping or not
  silence_log: True # output the logs or not
  sensor_cad_path: ./cad/kitti_car.ply
  mesh_min_nn: 7
  save_map: True
  save_mesh: True