setting:
  name: "wudasuidao"
  output_root: "./experiments"
  # pc_path: "./data/wudasuidao/backup/suidao_only/ply"
  # pose_path: "./data/wudasuidao/backup/suidao_only/poses.csv"
  pc_path: "./data/wudasuidao/normal/30frame/ply_normalcorrect_dir_100_kout_15"
  pose_path: "./data/wudasuidao/normal/30frame/poses.csv"
process:
  min_range_m: 0.5
  max_range_m: 40.0
  min_z_m: -30.0
  vox_down_m: 0.05
sampler:
  surface_sample_range_m: 0.25 # 在表面采样的大小，0.15m
  surface_sample_n: 3 # normal guided
  free_sample_begin_ratio: 0.4 # 开始采样点的地方
  free_sample_end_dist_m: 0.5 # 最大在behind surface上采样的距离，会转为free_sample_end_dist / repeated_dist + 1.0
  free_front_sample_n: 3
neuralpoints:
  voxel_size_m: 0.15
  query_nn_k: 8 # 在训练的时候用了8个点进行插值训练
  search_alpha: 0.5
  weighted_first: False
loss:
  sigma_sigmoid_m: 0.08
  loss_weight_on: True
  dist_weight_scale: 0.5
  ekional_loss_on: True
  weight_e: 0.5
  numerical_grad_on: False
continual:
  batch_size_cur_frame: 2000
  pool_capacity: 2e7
tracker:
  track_on: False
  source_vox_down_m: 0.2
  iter_n: 100
optimizer:
  mapping_freq_frame: 1
  iters: 50
  batch_size: 8192 # 8192 ， 16384
eval:
  wandb_vis_on: False # log to wandb or not
  o3d_vis_on: True # visualize the mapping or not
  silence_log: True # output the logs or not
  mesh_freq_frame: 20 # reconstruct the mesh every x frames
  mesh_min_nn: 7
  save_map: True
  save_mesh: True